spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/market
        driver-class-name: org.mariadb.jdbc.Driver
        username: nohji
        password: 1234

    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update

